### ISSUE TITLE
Exploring Github Repos

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#10]
In assignment #1, we are asked to explore repositories we like and put the research on a wiki page.
You can see an example here from last year:  https://github.com/bounswe/bounswe2019group7/wiki/Favourite-Repos

We need to create a common wiki page for this as well.

You can share the repo links here as well, so we can see more samples.

@olcaytoturker is an assignee as well. 

- [x] Burak Çuhadar
- [x] Koray Çetin
- [x] Eylül Yalçınkaya
- [x] Mehmet Erdinç Oğuz
- [x] Emre Girgin
- [x] Salih Kasım Benli
- [x] Berke Özdemir
- [x] Katariina Korolainen
- [ ] Berkay Alkan
- [ ] Muhammed Olcayto Türker
- [ ] Çağrı Çiftçi

**Comment by egirgin** [comment]
Favorite GitHub Repos wiki page is created by @burakcuhadar .
Link : https://github.com/bounswe/bounswe2020group4/wiki/Favourite-GitHub-Repos

**Comment by koraycetiin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exploring Github Repos](https://trello.com/c/CjidkZNv/36-exploring-github-repos)
