### ISSUE TITLE
Gateway timeout error on Nearest Vendor

### ISSUE THREAD

**Issue by koraycetiin** [bounswe/bounswe2020group4#107]
**Describe the bug**
Nearest vendor request isn't getting response due to a GATEWAY TIMEOUT error on amazon. It works on local, I've tested it with postman. Also tests are working fine.

**To Reproduce**
1. Go to http://bounswe2020group4.eu-west-1.elasticbeanstalk.com/
2. Click on Google Maps in the nearest vendor box
3. Look at the requests from the Network tab on developer tools, wait for the 'nearest' response.

**Expected behavior**
Get the response correctly and navigate to the google maps.

**Screenshots**
![Screenshot from 2020-05-28 00-15-07](https://user-images.githubusercontent.com/44166359/83072996-5c1ac780-a078-11ea-8c2f-be69a9d4fcb6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by koraycetiin** [comment]
Here's the possible problem and solution that @egirgin 
https://docs.aws.amazon.com/cloudhsm/latest/userguide/ssl-offload-enable-traffic-and-verify-certificate.html 
https://stackoverflow.com/questions/5309910/https-setup-in-amazon-ec2

**Comment by egirgin** [comment]
Deprecated
