### ISSUE TITLE
Distibution of Project Implementation

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#110]
Each contributor will write what their preferences are for the project work. Contributor will list the which area to work on according to the their priority, and describe their previous experiences(optional) 

Example:

1. Backend - worked in X company, implemented sorting functionality for products in NodeJS for backend.
2. Frontend
3. Android

**Comment by merijjeyn** [comment]
1. Backend - worked in Carla Car Rental. Implemented many new features using Kotlin, Java
2. Frontend - worked in Carla Car Rental. Somewhat experienced in using React with Redux. Open to being the joker between frontend and backend
3. Android - No prior experience

**Comment by olcaytoturker** [comment]
1. Backend - worked in Lumnion, implemented many features for a using ElectronJS and Python.
2. Frontend - worked in Lumnion, made few contribution using HTML and Javascript.
3. Android - No experience.

**Comment by BCGpp** [comment]
Prefer backend or frontend. I have approximate knowledge of many things.
No android xp here either.

**Comment by alprnbg** [comment]
1. Backend - Hobby project experience with PHP, Django and Node.js. Good experience with machine learning deployment on the cloud (if we want to use ML in the project)
2. Android - Very little experience with native android dev using Java (a simple tutorial project)
3. Frontend - No experience, just basics of CSS and HTML

**Comment by burakcuhadar** [comment]
1. Frontend - used react for one month in part-time job, just the basics
2. Backend - learned about node.js a litte bit more after we used it in 352
3. Android - no experience

**Comment by koraycetiin** [comment]
1. Backend: I have 10 months of experience in Sociable, 4 months of really soft experience in Insider. Currently working as Backend Developer in Codeway. All of my experiences was with NodeJS.
2. Frontend: Worked as web developer in Insider using JS, HTML, CSS for 9 months.
3. Android: 2 months of full stack experience in Sociable, didn't deal with hard features.

**Comment by cagric0** [comment]
1. Android: 10 months of experience with native android in SOLID-ICT.
2. Backend: little experience in Node JS. (Currently working as Backend Developer)
3. Frontend: Basic React knowledge

**Comment by egirgin** [comment]
1. Backend: used basic Flask and Django before
2. Android: Implemented some tutorials 
3. Frontend: Only pure HTML/CSS/JS and a little bit JQuery

**Comment by berkayalkan** [comment]
1. Backend: Experience in Spring, Java. Implemented APIs, made deployments on cloud. 
2. Frontend: Pure HTML, CSS, JS experience at basic level.
3. Android: No experience before, basic React Native knowledge.

**Comment by eylulyalcinkaya** [comment]
1. Frontend: HTML/CSS/JS
2. Backend: Python, Flask, Django
3. Android: -

**Comment by multiminparvo** [comment]
1. Backend - worked as part-time developer at Insider & Trendyol for 2 years.  I coded backend server, web services and cron jobs with nodeJs , python and php.
2. Frontend - worked as part-time developer at Insider. I used html, css,js, and jquery
3. Android - No  experience but I can work on it if it is needed.

**Comment by eridincu** [comment]
1. Backend: 6 months of experience in Google using C++ and Java, used basic Flask/Django and NodeJS.
2. Frontend: 2 months of experience in ReactJS in HemenIs, HTML/CSS
3. Android: Basic Flutter/Dart experience

**Comment by egirgin** [comment]
Teams are formed as the following: 

Backend Team: @koraycetiin @olcaytoturker @multiminparvo @eridincu 
Frontend Team: @merijjeyn @burakcuhadar @eylulyalcinkaya @BCGpp 
Android Team: @cagric0 @alprnbg @berkayalkan @egirgin
