### ISSUE TITLE
Project Plan Review

### ISSUE THREAD

**Issue by cagric0** [bounswe/bounswe2020group4#113]
Updating the project plan for the new semester according to the requirements.

Deadline: 01.11.2020 @23.59

**Comment by koraycetiin** [comment]
Here's the meeting notes that may help you https://github.com/bounswe/bounswe2020group4/wiki/2nd-Meeting---28.10.2020

**Comment by eridincu** [comment]
[BUYO.pdf](https://github.com/bounswe/bounswe2020group4/files/5469192/BUYO.pdf)

The 1st draft of the Project Plan. 
@multiminparvo @cagric0 I'd be glad if you can review it :)

In case you need it: 

[BUYO.pod file](https://github.com/bounswe/bounswe2020group4/blob/master/BUYO.pod)

You can open the file using [Project Libre](https://sourceforge.net/projects/projectlibre/).

Thanks!

**Comment by egirgin** [comment]
Please do not forget to update [Project Plan Page](https://github.com/bounswe/bounswe2020group4/wiki/Project-Plan) at wiki after you concluded.

**Comment by eridincu** [comment]
> Please do not forget to update [Project Plan Page](https://github.com/bounswe/bounswe2020group4/wiki/Project-Plan) at wiki after you concluded.

Done. Closing the issue.

**Comment by eridincu** [comment]
This issue is deprecated.

To track the progress about project plan, see [issue137](https://github.com/bounswe/bounswe2020group4/issues/137).
