### ISSUE TITLE
Learning Backend Technologies and Creating Extra Data

### ISSUE THREAD

**Issue by multiminparvo** [bounswe/bounswe2020group4#117]
Deadline: 08.11.2020
Backend Team should be confident about writing code to the server.

* We will work on how to write code by using Node JS
* We will work on how to use Docker
* We will try to do our first deployment
* We will find extra data for our database

**Comment by multiminparvo** [comment]
Backend Team will meet on Sunday for this issue if it is needed.

**Comment by multiminparvo** [comment]
- First deployment is done
- Learning part is done
- We are adding the example data on this page: 
https://github.com/bounswe/bounswe2020group4/wiki/BUYO-Product-Data

**Comment by koraycetiin** [comment]
I've added some products in Product-Data page, they may be enough for us.
