### ISSUE TITLE
(AND) Product detail page

### ISSUE THREAD

**Issue by cagric0** [bounswe/bounswe2020group4#118]
Milestone 1 - Android Implementation

![image](https://user-images.githubusercontent.com/44342412/98123975-a4f66800-1ec3-11eb-8dd3-8fc84199023d.png)

Deadline: 22.11.2020 Sunday 18.30

**Comment by egirgin** [comment]
First draft:
![image](https://user-images.githubusercontent.com/25237088/98484180-b2db1e80-221e-11eb-81bd-8ee3d0719026.png)
Comments section is converted to a button. Comments layout is going to be designed later.

**Comment by alprnbg** [comment]
Can you send the blueprint SS with constraints are visible?

**Comment by egirgin** [comment]
![image](https://user-images.githubusercontent.com/25237088/98583605-aebe0800-22d5-11eb-84d7-2e3c9f193545.png)
I guess, this is the schema you wanted to.

**Comment by egirgin** [comment]
![image](https://user-images.githubusercontent.com/25237088/99380671-51304980-28db-11eb-95f8-45e083f1567c.png)
![image](https://user-images.githubusercontent.com/25237088/99380689-555c6700-28db-11eb-82c3-cbd230382b21.png)
Product detail and comment fragments

**Comment by egirgin** [comment]
Closes [PR ](https://github.com/bounswe/bounswe2020group4/pull/155)
