### ISSUE TITLE
(AND) Product list page

### ISSUE THREAD

**Issue by cagric0** [bounswe/bounswe2020group4#119]
Milestone 1 - Android Implementation

![image](https://user-images.githubusercontent.com/44342412/98124474-4a114080-1ec4-11eb-8826-0192211f7b9b.png)

Deadline: 22.11.2020 Sunday 18.30

**Comment by egirgin** [comment]
![image](https://user-images.githubusercontent.com/25237088/99383412-e123c280-28de-11eb-921b-2cd17e288fd4.png)

**Comment by egirgin** [comment]
closes [PR](https://github.com/bounswe/bounswe2020group4/pull/156)
