### ISSUE TITLE
(AND) Learning some Android core topics

### ISSUE THREAD

**Issue by cagric0** [bounswe/bounswe2020group4#121]
Some of the important elements are determined: - recycler view, activity, fragment, constraint layout, retrofits, viewmodel, glide etc.

Deadline: 10.11.2020 Tuesday 18.30

**Comment by egirgin** [comment]
- There is a Youtube [playlist](https://youtu.be/3Ri9PPsGCEg) that covers most of the techs mentioned above and prepared for beginners.
- [Developer Android](https://developer.android.com/)
