### ISSUE TITLE
(AND) Log-in/Sign-up

### ISSUE THREAD

**Issue by alprnbg** [bounswe/bounswe2020group4#122]
* UI implementation of the Login/Signup page for Android app. This page will be reached from the My Account button which is on the homepage.
* In this page user will sign up or log in with password and username.
* User can sign up using his/her google account. (This issue does not contain this feature, it will be implemented later.)

### Simple Page Layout
![Screen Shot 2020-11-04 at 17 33 07](https://user-images.githubusercontent.com/35741925/98124893-cefc5a00-1ec4-11eb-8496-2b7bb6585774.png)

Deadline: 22.11.2020 18:30 (updated)

**Comment by alprnbg** [comment]
First draft is ready. Google sign-up is not implemented yet, button is just there as a placeholder. Official "Sign up with Google" button will be used in production. 

Please review

![Screen Shot 2020-11-10 at 00 24 57](https://user-images.githubusercontent.com/35741925/98598236-34987e00-22eb-11eb-9888-47cbe1977864.png)

**Comment by egirgin** [comment]
**LGTM**

**Comment by alprnbg** [comment]
> **LGTM**
> 
> Edit: Maybe we want to add _I forgot my password_ section without functionality for the sake of the design phase.

Yes, I will add that asap, ty.
