### ISSUE TITLE
(AND) Homepage UI

### ISSUE THREAD

**Issue by berkayalkan** [bounswe/bounswe2020group4#125]
* UI implementation of the home page.
* Deadline : 10.11.2020 Tuesday 18:30

![Main Page](https://user-images.githubusercontent.com/44069799/98125155-2f8b9700-1ec5-11eb-8480-5173c6cbd981.jpg)

**Comment by alprnbg** [comment]
* I created a draft for homepage, you can find the screenshot below. When base app is done, I can create a new branch and a pull request afterwards. 
* Recycle views are just a placeholder now, but they will change a lot when we start to implement functionality. 
* NavBar will be added later. It will be implemented as another activity or fragment. 
Can you review it?  

![Screen Shot 2020-11-09 at 00 22 02](https://user-images.githubusercontent.com/35741925/98484647-0b5feb00-2222-11eb-964e-efa1ae1cd088.png)

**Comment by alprnbg** [comment]
Forgot my password button is missing

**Comment by egirgin** [comment]
Closes [PR](https://github.com/bounswe/bounswe2020group4/pull/157)
