### ISSUE TITLE
(AND) Wishlist

### ISSUE THREAD

**Issue by alprnbg** [bounswe/bounswe2020group4#126]
* UI implementation of wishlist and collection page. This page will be reached from the homepage (Favorites button).
![Wishlist Page](https://user-images.githubusercontent.com/44069799/98600816-3401e680-22ef-11eb-943a-be26e578d8d5.png)
Deadline: 10.11.2020 18.30

**Comment by berkayalkan** [comment]
First draft:

![Ekran Görüntüsü (62)](https://user-images.githubusercontent.com/44069799/98624352-a50cc280-231e-11eb-81b4-eddf51677391.png)

Logics will be implemented later. 
Please review. @alprnbg @egirgin @cagric0
