### ISSUE TITLE
Use Case Diagram Updates

### ISSUE THREAD

**Issue by multiminparvo** [bounswe/bounswe2020group4#133]
We will talk about the use case diagrams and update according to the features
Deadline: 15.11.2020

**Comment by egirgin** [comment]
I guess we assigned class and sequence diagrams to backend and use-case diagrams to frontend&android teams. May there be a misunderstanding ? [Meeting Notes](https://github.com/bounswe/bounswe2020group4/wiki/4th-Meeting-10.11.2020)

**Comment by egirgin** [comment]
[Use-case](https://lucid.app/invitations/accept/958a3910-5ebe-4ca7-b9f8-dc3e7cf6ee59)

**Comment by egirgin** [comment]
- Forget password case added. 
- List converted to collection.
- View profile page and enter name and address.
- Create a campaign use case added. 
- Customer complaint added.
