### ISSUE TITLE
(AND) Finalize the Project Plan

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#135]
Android team will update the Project Plan to shape it into its final form.

Deadline: 19/11/20

**Comment by egirgin** [comment]
Is there a google sheet for this or we directly download and write into project libre (.pod) file. I think we need a google sheet to be synchronized.

**Comment by egirgin** [comment]
[PDF](https://github.com/bounswe/bounswe2020group4/blob/master/ProjectPlan%26RAM/BUYO.pdf)
[POD](https://github.com/bounswe/bounswe2020group4/blob/master/ProjectPlan%26RAM/BUYO.pod)
