### ISSUE TITLE
(BKND) Finalize the Project Plan

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#136]
Backend team will update the Project Plan to shape it into its final form.

Deadline: 19/11/20

**Comment by eridincu** [comment]
I updated the Project plan documents, please check:

[PDF](https://github.com/bounswe/bounswe2020group4/blob/master/ProjectPlan%26RAM/BUYO.pdf)
[POD](https://github.com/bounswe/bounswe2020group4/blob/master/ProjectPlan%26RAM/BUYO.pod)

**Comment by multiminparvo** [comment]
The task management and deadlines seem legitimate to me. Good work @eridincu
