### ISSUE TITLE
Review and Update of Requirements

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#138]
We need to update our requirements for the decisions taken after [4th meeting](https://github.com/bounswe/bounswe2020group4/wiki/4th-Meeting-10.11.2020).

Deadline : 17.11.2020 Tuesday

**Comment by egirgin** [comment]
- Collection(sub-wishlist) and wishlist interaction and relation are needed to be clarified.
- Forgot my password and customer complaint is added to Requirements by @burakcuhadar last week.
- Customer needs to provide name, surname and, address before s/he orders a product.
- In comments, the name and surname of the user must be hidden always.
- Customer can change their addresses during the ordering process and their profile page.
- Customers can name their subwishlists (collections)
- There might be an empty collection.
- Wishlist now have a separate header in requirements.
- Filter by category added.
- Users shall be able to filter available for that category.
- Filtering mechanism is going to be discussed together as a 12 ppl team.
- When a product is removed from collection it is NOT removed from wishlist but when a product removed from wishlist, it is also removed from the collection it is belong to. 
- If there is a campaign or discount in the product which is in a collection or wishlist, then the customer get notified.
- Cargo option is default BuyoExpress
- Payments are accepted only in Turkish Lira.

**Comment by egirgin** [comment]
Backend team: @multiminparvo @koraycetiin @eridincu @olcaytoturker Please check our updates on requirements and let us know if there is something infeasible in terms of backend development.

**Comment by multiminparvo** [comment]
It seems ok to me. If you dont have any further comments , we can close this issue @koray-cetin @eridincu  @olcaytoturker

**Comment by olcaytoturker** [comment]
It seems okay to me too.
