### ISSUE TITLE
Review and Update of Sequence Diagrams

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#139]
We need to update our sequence diagrams for the decisions taken after[ 4th meeting.](https://github.com/bounswe/bounswe2020group4/wiki/4th-Meeting-10.11.2020)

Deadline : 17.11.2020 Tuesday

**Comment by eridincu** [comment]
Added the sequence diagram of "Show Product" https://github.com/bounswe/bounswe2020group4/blob/master/cmpe352/diagrams/sequence_diagrams/show%20product.png

**Comment by koraycetiin** [comment]
Added the Get Products of a Category sequence diagram
https://github.com/bounswe/bounswe2020group4/blob/master/cmpe352/diagrams/sequence_diagrams/sequence.png

**Comment by multiminparvo** [comment]
The sequence diagram of searching a product is added:
https://github.com/bounswe/bounswe2020group4/blob/master/cmpe352/diagrams/sequence_diagrams/Search%20Diagram.png

**Comment by eridincu** [comment]
Diagrams have been added by all the assignees.
