### ISSUE TITLE
Documenting Meeting Notes #2

### ISSUE THREAD

**Issue by burakcuhadar** [bounswe/bounswe2020group4#14]

**Comment by burakcuhadar** [comment]
I have prepared the wiki page for meeting notes. Please feel free to correct the mistakes I have done or add the things I forgot to write. I also could not write full names of some people(sorry guys), because I don't know them. If they would have personal wiki pages, I could write their full names.

**Comment by koraycetiin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documenting Meeting Notes #2](https://trello.com/c/3ors9EsY/34-documenting-meeting-notes-2)
