### ISSUE TITLE
Extracting Requirements

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#15]
The requirements of the project are going to be extracted from the [Project Desc.](https://piazza.com/class_profile/get_resource/k5z7hzm7ncm1m3/k6nyj71rmhq19f)

Deadline: 21.02.2020 Friday @24.00

**Comment by koraycetiin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Extracting Requirements](https://trello.com/c/z8tEqakW/24-extracting-requirements)

**Comment by zeritte** [comment]
https://github.com/bounswe/bounswe2020group4/wiki/Abstraction-of-the-description
