### ISSUE TITLE
Categorizing Requirements

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#16]
Categorizing the extracted requirements.

Deadline: 22.02.2020 Saturday @24.00

**Comment by koraycetiin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Categorizing Requirements](https://trello.com/c/f3FthKyk/26-categorizing-requirements)

**Comment by egirgin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Categorizing Requirements](https://trello.com/c/f3FthKyk/26-categorizing-requirements)

**Comment by egirgin** [comment]
Extracted requirements are categorized. 
[Link](https://github.com/bounswe/bounswe2020group4/wiki/Abstraction-of-the-description)
