### ISSUE TITLE
Writing Requirements

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#17]
Writing categorized requirements and glossary formally into a wiki page.

Deadline: 24.02.2020 Monday @24.00

**Comment by koraycetiin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Writing Requirements](https://trello.com/c/5Xux5Tse/27-writing-requirements)

**Comment by burakcuhadar** [comment]
https://github.com/bounswe/bounswe2020group4/wiki/Requirements-Specification
