### ISSUE TITLE
W3C Research

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#18]
Research into World Wide Web Consortium (W3C) and W3C Activity Streams protocols.

**Comment by koraycetiin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Research about W3C](https://trello.com/c/niBap6Pg/23-research-about-w3c)

**Comment by egirgin** [comment]
Very informative. Well done @eridincu . [W3C Standarts](https://github.com/bounswe/bounswe2020group4/wiki/W3C-Standards) and [W3C Activity Streams](https://github.com/bounswe/bounswe2020group4/wiki/W3C-Activity-Streams)
