### ISSUE TITLE
About Public Name

### ISSUE THREAD

**Issue by mericturan** [bounswe/bounswe2020group4#181]
Dear @merijjeyn and @zeritte,

In our last lab session, I have warned you about associating your real name with your GitHub account using [profile settings page](https://github.com/settings/profile). Please complete this task ASAP.

**Comment by zeritte** [comment]
dear @mericturan :)
I have graduated from the university. Feel free to remove me from the repository

**Comment by merijjeyn** [comment]
Sorry about that, should be good now.
