### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#19]
The license of the project needs to be decided.

Some of the popular licenses by comparison:
https://choosealicense.com/licenses/

How to add license to project:
https://stackoverflow.com/a/31666878/10091826
or this:
https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository
or here:
https://github.com/bounswe/bounswe2020group4/community

The link Suzan Hoca shared:
https://www.wired.com/story/open-source-license-requires-users-do-no-harm/

**Comment by egirgin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Licensing](https://trello.com/c/xa9eDoYz/39-licensing)

**Comment by eridincu** [comment]
I guess "GNU GPLv3.0(General Public License v3.0)" license is suitable for our project.
