### ISSUE TITLE
(Milestone 1) Status and evaluation of deliverables

### ISSUE THREAD

**Issue by eylulyalcinkaya** [bounswe/bounswe2020group4#204]
List and status of deliverables.
Evaluation of the status of deliverables and their impact on the plan.

- [x] Backend
- [x] Frontend
- [x] Android

Deadline: @17.30 29.11.2020

**Comment by egirgin** [comment]
Android part was added. 28.11.2020 18.00

**Comment by eridincu** [comment]
Backend part was added on 28.11.2020 at 18.03
