### ISSUE TITLE
(Milestone 1) Project plan

### ISSUE THREAD

**Issue by eylulyalcinkaya** [bounswe/bounswe2020group4#210]
Project plan (in tabular format; you may omit Gantt timelines and display dates/durations/assignees/predecessors only as a text for readability. Unreadable plans will NOT be graded.).

Deadline: @17.30 29.11.2020

**Comment by eridincu** [comment]
Added to the doc. Could you please review? @multiminparvo @eylulyalcinkaya @cagric0

**Comment by eridincu** [comment]
Reviewed by @egirgin in Google Docs.
