### ISSUE TITLE
(Milestone 1) Evaluation of tools and managing the project

### ISSUE THREAD

**Issue by eylulyalcinkaya** [bounswe/bounswe2020group4#213]
This is a lesson learned from the project development decisions made so far. Tools are for planning, IDE, frameworks, and everything. The management is the process used by the team, including how the tools are being effectively utilized. If there are some aspects that are not working out, what kind of changes are planned.

Deadline: @17.30 29.11.2020

**Comment by berkayalkan** [comment]
Android part is done.

**Comment by multiminparvo** [comment]
Backend part is done
