### ISSUE TITLE
(Milestone 1) Assessment of the customer presentation

### ISSUE THREAD

**Issue by eylulyalcinkaya** [bounswe/bounswe2020group4#214]
What did you learn from your interaction about the status and direction of your project? Also, did you learn anything about presenting? Difficulties? What went well, what needs improvement for next time.

Deadline: @17.30 29.11.2020

**Comment by alprnbg** [comment]
I wrote this part. @burakcuhadar you can review and edit it. Then, we can close the issue.

**Comment by burakcuhadar** [comment]
Thanks @alprnbg. I reviewed what you wrote and added a paragraph about frontend presentation.
