### ISSUE TITLE
Fix the requirements considering the feedback

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#22]
Change the requirements considering the instructor's feedback.

**Comment by egirgin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the requirements considering the feedback](https://trello.com/c/BxdpgL3N/43-fix-the-requirements-considering-the-feedback)

**Comment by katakor** [comment]
There was no mention of this in the feedback, but I think it could be beneficial to specify the term "user" in the requirements. For example, in cases like "Users shall message with vendors directly" or "Users shall comment on products" I think we mean logged in users (Customer/Vendor). I can go through these if you agree

**Comment by egirgin** [comment]
You are right @katakor . It would be better if you handle that.
