### ISSUE TITLE
(AND) Product Detail Page Update

### ISSUE THREAD

**Issue by berkayalkan** [bounswe/bounswe2020group4#225]
- More detailed info need to be added to product detail 
**Deadline:** 08.12.2020

**Comment by egirgin** [comment]
The UI and the logic is implemented but backend connection waits for the endpoint to be implemented/live.

Checkout **android-dev-productDetail** branch for commits.

**Comment by egirgin** [comment]
#267 #285

**Comment by egirgin** [comment]
[Commit](https://github.com/bounswe/bounswe2020group4/commit/743cce27aea75c053a6d235d7846e1de289b974c)
