### ISSUE TITLE
(AND) Vendor Sing up - Login UI

### ISSUE THREAD

**Issue by cagric0** [bounswe/bounswe2020group4#227]
It will be added to Login Page UI 
Deadline: 08.12.2020

**Comment by alprnbg** [comment]
Name, surname, company website (instead of TR Tax Id), company e-mail should be added.

**Comment by alprnbg** [comment]
Popular domains should be added to black list.

**Comment by alprnbg** [comment]
Back button should be put on the map fragment and legal docs.

**Comment by alprnbg** [comment]
Everything fixed. I will open PR soon, when order page is implemented.
