### ISSUE TITLE
(BKND) Create English Database & Adding Some Attributes

### ISSUE THREAD

**Issue by multiminparvo** [bounswe/bounswe2020group4#234]
Deadline: 14 Dec.
We created our database by using Turkish data. Our application language is English.
We have to convert our database to English.

**Comment by multiminparvo** [comment]
I couldnt find any English Ecommerce website db.I had to translate it one by one. 
I am increasing the effort of this task to high.

**Comment by multiminparvo** [comment]
New Data Format:
        {
            "image_url": "https://img-lcwaikiki.mncdn.com/mnresize/230/-/pim/productimages/20202/4353680/l_20202-0w9038z1-qca_a.jpg",
            "sizeList": ["S","M","L"],
            "sizeStockInfo": {"S":20,"M":20,"L":20},
            "description": "100% Natural. 100% Nature Friendly.",
            "name":  "2-pack Baby Girls Set",
            "item_id": "0W9038Z1_1048231",
            "url": "https://www.lcwaikiki.com/tr-TR/TR/urun/LC-WAIKIKI/kiz-bebek/Takim/4353680/1048231?#ins_sr=eyJwcm9kdWN0SWQiOiIwVzkwMzhaMV8xMDQ4MjMxIn0%3D",
            "in_stock": 1,
            "price": {
                "TRY": 35.99
            },
            "locale": "tr_TR",
            "product_attributes": {
                "addtocartproductids": "[{\"addToCartProductId\":10202213,\"sizeText\":\"12-18 Months\"},{\"addToCartProductId\":10202214,\"sizeText\":\"18-24 Months\"},{\"addToCartProductId\":10202215,\"sizeText\":\"24-36 Months\"},{\"addToCartProductId\":10202216,\"sizeText\":\"3-4 Year\"},{\"addToCartProductId\":10202217,\"sizeText\":\"4-5 Year\"},{\"addToCartProductId\":10202218,\"sizeText\":\"6-9 Months\"},{\"addToCartProductId\":10202219,\"sizeText\":\"9-12 Months\"}]",
                "one_size": false,
                "product_modal_id": "4353680"
            },
            "category": [
                "Baby",
                "Baby Girl",
                "Sets"
            ],
            "discount": {
                "TRY": 0
            },
            "original_price": {
                "TRY": 35.99
            }
        },

**Comment by koraycetiin** [comment]
Veli translated clothing products, i'll translate cosmetic products and add them to db.
