### ISSUE TITLE
Legal documents

### ISSUE THREAD

**Issue by eylulyalcinkaya** [bounswe/bounswe2020group4#254]
These are the legal documents needed for the project:
- [x] GDPR/KVKK @alprnbg 
- [x] Üyelik sözleşmesi @merijjeyn 
- [x] Mesafeli satış sözleşmesi @burakcuhadar 
- [x] Ön bilgilendirme sözleşmesi @multiminparvo 

Deadline: 26.12.2020

**Comment by multiminparvo** [comment]
You can find the legal documents in this file:
https://github.com/bounswe/bounswe2020group4/tree/master/Legal%20Docs
