### ISSUE TITLE
Prepare the Communication Plan and the Meeting Notes

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#26]
Eylül will prepare the communication plan and meeting notes.

**Comment by eylulyalcinkaya** [comment]
[Meeting notes](https://github.com/bounswe/bounswe2020group4/wiki/3rd-Meeting---27.02.2020]) can be found here.

**Comment by egirgin** [comment]
@eylulyalcinkaya looks great. However, let us keep this issue open until all of us fill the **Completion Time** column at [action items table](https://github.com/bounswe/bounswe2020group4/wiki/W3C-Activity-Streams) as well.

**Comment by eylulyalcinkaya** [comment]
Updated version of communication plan can be found [here](https://github.com/bounswe/bounswe2020group4/wiki/Communication-Plan)

**Comment by eylulyalcinkaya** [comment]
> @eylulyalcinkaya looks great. However, let us keep this issue open until all of us fill the **Completion Time** column at [action items table](https://github.com/bounswe/bounswe2020group4/wiki/W3C-Activity-Streams) as well.

I think it is better if we open a different issue for that, since I am the only assignee in this one.
