### ISSUE TITLE
Prepare the web app scenario for the Vendor.

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#29]
Prepare and document the vendor scenario **until Sunday 23.59.**

**Comment by egirgin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prepare the web app scenario for the Vendor.](https://trello.com/c/AK7NRwsR/49-prepare-the-web-app-scenario-for-the-vendor)

**Comment by egirgin** [comment]
[moqups](https://moqups.com/) is a good mockup design website running on browser. It has even an E-Commerce Shop Wireframe.

**Comment by egirgin** [comment]
@zeritte and I wrote a [scenario and mock-up](https://github.com/bounswe/bounswe2020group4/wiki/Vendor-WebApp-Scenario&Mock-up) for it. Please check that out.

**Comment by katakor** [comment]
Good job! The only thing I changed was numerating the actions & steps in the mock-up
