### ISSUE TITLE
(BUG) Product sizes key names

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#290]
**Describe the bug**
After sending request like _http://3.138.113.101:8080/product?id=5fe0e6b92a7614001204688a_  in _stockValue_ field contains a dictionary with keys like **XS-Purple**, which can not be used as a variable name. 

**To Reproduce**
1. Send a request to the endpoint mentioned above
2. See the response

**Expected behavior**
Sizes information needed to be kept in the form of **XS_Purple**

**Screenshots**
Sample response :
```json
{"status":{"code":200,"message":"OK"},"data":{"result":{"category":["Kids","Boy","Sportswear"],"sizes":["XS"],"colors":["Red","Blue","White","Purple","Orange"],"description":"100% Natural. 100% Nature Friendly. It will definitely look good on you. You won't regret buying this.","name":"Men's Hooded Sweatshirt with Zipper","price":34.99,"originalPrice":49.99,"imageUrl":"https://img-lcwaikiki.mncdn.com/mnresize/230/-/productimages/20201/4/3824376/l_20201-0s1544z4-noo_a.jpg","rating":0.15,"brand":"Watsons","stockValue":{"XS-Red":87,"XS-Blue":83,"XS-White":90,"XS-Purple":63,"XS-Orange":12},"vendor":{"name":"AyseTeyze","rating":3.21},"id":"5fe0e6b92a7614001204688a","comments":[]}}}
```

**Comment by koraycetiin** [comment]
This structure is changed with this pull, https://github.com/bounswe/bounswe2020group4/pull/282.
Now Veli is fixing the product responses.

**Comment by koraycetiin** [comment]
Veli fixed the product responses.
