### ISSUE TITLE
Prepare the mobile app scenario for the Guest.

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#30]
Prepare and document the mobile app scenario for the Guest **until Sunday 23.59.**

**Comment by egirgin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prepare the mobile app scenario for the Guest.](https://trello.com/c/lfeml00g/50-prepare-the-mobile-app-scenario-for-the-guest)

**Comment by eridincu** [comment]
https://github.com/bounswe/bounswe2020group4/wiki/Scenario:-Guest-user the link for the wiki, handy to have it here :)

**Comment by egirgin** [comment]
> https://github.com/bounswe/bounswe2020group4/wiki/Scenario:-Guest-user the link for the wiki, handy to have it here :)

Looks great. Good job. 👍
