### ISSUE TITLE
(BUG) /account endpoint not working

### ISSUE THREAD

**Issue by eylulyalcinkaya** [bounswe/bounswe2020group4#316]
/account endpoint does not work.

**To Reproduce**
1. On Postman, I sent this GET request: `http://3.138.113.101:8080/account?id=5fccefb77fa83900125956c1&userType=customer`
2. 5fccefb77fa83900125956c1 is an already existing userId that I can get by this request: `http://3.138.113.101:8080/login?userType=customer&email=abcde@hotmail.com&password=1234`
3. The response is `Cannot GET /account`

**Expected behavior**
Return account information of the customer

**Comment by koraycetiin** [comment]
We reverted our latest commit for the last demo, unfortunately account endpoint is not deployed right now. We'll be dealing with it ASAP.
