### ISSUE TITLE
Interview with Customer and Get Answers to Our Questions

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#32]
The assignees should meet with the customer(assistant teacher) and get answers to our answers about our project.

**Comment by egirgin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Interview with Customer and Get Answers to Our Questions](https://trello.com/c/5tgybThj/52-interview-with-customer-and-get-answers-to-our-questions)
