### ISSUE TITLE
(BKND) Get Profile Info

### ISSUE THREAD

**Issue by olcaytoturker** [bounswe/bounswe2020group4#321]
Get profile endpoint will be changed regarding to decisions have been made in the last group meeting.

**Deadline**
27/12/20

**Comment by eylulyalcinkaya** [comment]
Fields that we should have for customer profile are: first name, last name, email, phone number and gender(for gender: empty, female, male, other, no info)

**Comment by olcaytoturker** [comment]
> Fields that we should have for customer profile are: first name, last name, email, phone number and gender(for gender: empty, female, male, other, no info)

It will return all information of customer user you mentioned if he/she adds these informations to his/her profile.
If not added yet, it will return email only because we only get email and password in signup.
