### ISSUE TITLE
(BUG) Product detail page not working

### ISSUE THREAD

**Issue by eylulyalcinkaya** [bounswe/bounswe2020group4#323]
Product detail page returns an error.

**To Reproduce**
1. Go to `http://localhost:3000/products?categories=Supermarket,Detergent+and+Cleaning+Products#`
2. Click on one of the products. It redirected to `http://localhost:3000/product/5fe2112c2a76140012047a68` for one of them.
3. See error `Unhandled Rejection (TypeError): response.data.data.products.find is not a function` in `isInWishlist src/services/wishlist.js:22` and in `async isInWishlist src/components/WishlistButton.js:24`

**Expected behavior**
Product detail page of the product that I clicked on.

**Desktop (please complete the following information):**
 - OS: MacOS 11.1
 - Browser: Chrome

**Comment by koraycetiin** [comment]
I think in 22nd line in web/src/services:
response.data.data.products.find(p => p.id === productId) !== undefined
the code should be like this:
response.data.products.find(p => p.id === productId) !== undefined

I couldn't see any problem in wishlist endpoint

**Comment by koraycetiin** [comment]
I think in 22nd line in web/src/services:
response.data.data.products.find(p => p.id === productId) !== undefined
the code should be like this:
response.data.products.find(p => p.id === productId) !== undefined

I couldn't see any problem in wishlist endpoint

**Comment by koraycetiin** [comment]
Sorry i thought this was backend issue :)

**Comment by burakcuhadar** [comment]
Can you try with a different user? Backend has changed user ids, i think you are logged in with an old user which does not exist. Since we do not have sign out functionality, you can delete history or use private mode :D

**Comment by eylulyalcinkaya** [comment]
> Can you try with a different user? Backend has changed user ids, i think you are logged in with an old user which does not exist. Since we do not have sign out functionality, you can delete history or use private mode :D

Yes, when I tried with a different user, it worked :) I'm closing the issue.
