### ISSUE TITLE
Making requirements more clear

### ISSUE THREAD

**Issue by zeritte** [bounswe/bounswe2020group4#33]
The email assistant sent includes various warnings about requirements. One of them is that:

> Requirements should be crystal clear.  For example in 2.1.1.1.1., you stated that “Searching products shall utilize all information available in product pages & vendor profiles.”. What you mean by saying “all information” is not clear. You should specify them. The same can be applied to many more.

We should fix the requirement related issues before **8th March**, which is the deadline for Requirements 1.0

**Comment by egirgin** [comment]
Fixing the requirements according to feedback is mentioned in [this issue](https://github.com/bounswe/bounswe2020group4/issues/22). @burakcuhadar and @cagric0 are assigned with [task number 2](https://github.com/bounswe/bounswe2020group4/wiki/3rd-Meeting---27.02.2020#action-items). Do you mean some other warning or the same?

**Comment by zeritte** [comment]
> Fixing the requirements according to feedback is mentioned in [this issue](https://github.com/bounswe/bounswe2020group4/issues/22). @burakcuhadar and @cagric0 are assigned with [task number 2](https://github.com/bounswe/bounswe2020group4/wiki/3rd-Meeting---27.02.2020#action-items). Do you mean some other warning or the same?

I saw it but thought it is obsolete since they want us to separate issues

**Comment by egirgin** [comment]
> > Fixing the requirements according to feedback is mentioned in [this issue](https://github.com/bounswe/bounswe2020group4/issues/22). @burakcuhadar and @cagric0 are assigned with [task number 2](https://github.com/bounswe/bounswe2020group4/wiki/3rd-Meeting---27.02.2020#action-items). Do you mean some other warning or the same?
> 
> I saw it but thought it is obsolete since they want us to separate issues
Okay. You are right.

**Comment by eridincu** [comment]
> > Fixing the requirements according to feedback is mentioned in [this issue](https://github.com/bounswe/bounswe2020group4/issues/22). @burakcuhadar and @cagric0 are assigned with [task number 2](https://github.com/bounswe/bounswe2020group4/wiki/3rd-Meeting---27.02.2020#action-items). Do you mean some other warning or the same?
> 
> I saw it but thought it is obsolete since they want us to separate issues

I think [that issue](https://github.com/bounswe/bounswe2020group4/issues/22) should stay until the requirements in the feedback satisfied. Also, creating new issues is a good practice, you are right. We can make the first issue as a root issue for smaller changes.

**Comment by eridincu** [comment]
Oops, wrong button.
