### ISSUE TITLE
Non-functional requirements need to be enlarged

### ISSUE THREAD

**Issue by zeritte** [bounswe/bounswe2020group4#35]
We can do this by adding availability and accessibility separately as well as security and privacy & by moving some functional one's to non-functionals requirements (e.g 1.2.3.3 is about Turkish chars to non-functionals)
We should fix the requirement related issues before 8th March, which is the deadline for Requirements 1.0

**Comment by egirgin** [comment]
Done [here](https://github.com/bounswe/bounswe2020group4/wiki/Requirements-Specification#2-nonfunctional-requirements)
