### ISSUE TITLE
(BUG) Credit Card Verification

### ISSUE THREAD

**Issue by koraycetiin** [bounswe/bounswe2020group4#354]
http://3.138.113.101:8080/order?customerId=5fe84543ff92960019545eae&creditCard={"name": "712837123","number": 1234666666667777,"expirationMonth": 10,"expirationYear": 24,"cvc": 999} this request brokes the order workflow, because credit card verification is not successful.

- Expiration year works when it's less than 20
- Backend is forcing the frontend to send strings in cvc and number fields. These number fields can be handled as well

**Comment by koraycetiin** [comment]
Also we could send an error message when credit card verification is failed

**Comment by eridincu** [comment]
Working on it.
