### ISSUE TITLE
(BUG) (BKND) Add to cart does not work

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#363]
**Describe the bug**
After adding a product to cart, although response is "success" (code:200) get cart response does not contain the added product

**To Reproduce**
1. Go to postman 
2. Send a post request:
```
http://3.138.113.101:8080/cart?customerId=5fe08a767fa83900125956d7&productId=5fe887b1e7fb86001254fd31&productInfo={"attributes":[{"name":"size","value":"42"},{"name":"color","value":"Black"}], "quantity":1}
```
3. See success response
4. Send a get request
```
http://3.138.113.101:8080/cart?customerId=5fe08a767fa83900125956d7
```
5. See the product is not in the cart

**Expected behavior**
The new added product should in the cart

**Screenshots**
![image](https://user-images.githubusercontent.com/25237088/103172471-cab94100-4864-11eb-8905-a2330fdcc0af.png)
![image](https://user-images.githubusercontent.com/25237088/103172474-d442a900-4864-11eb-8981-5d40efdde8bc.png)

**Desktop**
 - Postman

**Comment by eridincu** [comment]
Works good in my local computer, the problem might be caused by the deployed code.

**Comment by egirgin** [comment]
After the db is re-initialized, the problem seemed solved.
