### ISSUE TITLE
(BUG)(BKND) Products are not sorted by price

### ISSUE THREAD

**Issue by burakcuhadar** [bounswe/bounswe2020group4#366]
**Describe the bug**
When I try to sort the products by ascending price, they are not returned in correct order.

**To Reproduce**
1. GET http://3.138.113.101:8080/products?categories=["Cosmetics","Skincare"]&sortingFactor=price&sortingType=ascending
2. Observe that the products are not returned in correct order

**Expected behavior**
Products should be sorted by ascending price.

**Comment by multiminparvo** [comment]
Thanks for opening bug task @burakcuhadar 
Status: Waiting for review https://github.com/bounswe/bounswe2020group4/pull/374
Solution report: 
Type checking of the endpoint parameter was written in wrong way. Of course we tested this endpoint before, but we didnt notice the bug.

Previously: typeof products[0][params.sortingFactor] == Number
Correct way :typeof(products[0][params.sortingFactor]) == "number"
