### ISSUE TITLE
(BUG) Products from wishlist returned as an object instead of an array

### ISSUE THREAD

**Issue by merijjeyn** [bounswe/bounswe2020group4#381]
Products returned from wishlist was normally an array but in some cases it started to return an object which causes errors in some parts of the frontend. 

Not exactly sure about the steps to reproduce but seems like the error occurs when we try to get the wishlist of a user that has not added anything to its wishlist yet.

**Comment by koraycetiin** [comment]
I've tested it with empty wishlist case. Then send the request for all the users in the db, couldn't reproduce it. We're looking for the reason behind this.

**Comment by merijjeyn** [comment]
I have tested some more and I think there is a problem with that specific user.
My guess is that my already logged in user was an old one and it vanished when you resetted the database.

Anyways tested the scenario a couple of times and its fine so it is not critical for now

**Comment by multiminparvo** [comment]
If we face with the issue again, I will reopen the task.
It seems there is no issue currently
