### ISSUE TITLE
Fixing the scenarios

### ISSUE THREAD

**Issue by berkeozdemir2016400246** [bounswe/bounswe2020group4#39]
We need to fix scenarios according to the feedback given by the instructor in class, the customer in the meeting and rest of the team.

Deadline: 11.03.2020 @23.59

**Comment by katakor** [comment]
(From Meriç)

Below, you may find my feedbacks related to your scenarios and mock-ups. Please note that given feedback is not limited to ones below, you can apply similar comments to others if fits.

- [ ] Besides stating the requirement number, you should also specify the requirement itself in the acceptance criteria (not stated in **Sasha’s scenario**).

- [ ] The first mock-up (**customer mock-up**) does not contain a sufficient amount of real input data both in terms of text and image. Also, there is a Google ad, which should not exist in our platform. Also, during the checkout, you are showing recommended products to the user, which is absurd.

- [ ] There is a question mark in the second, fifth, and sixth items of the **vendor mock-up**. You should either re-upload it or change the resolution of the image to be seen. My suggestion is to remake the vendor mock-up from scratch.

- [ ] Also, similar comments to the **customer mock-up** apply here as well (e.g., no image of the product, no product details). 

- [ ] Very similar comments apply for **guest user** mock-up as well (e.g., no product name, no product image, no reviews). Also, does a guest user have to sign-in to buy a product?

**Comment by egirgin** [comment]
vendor scenario is renewed by Salih & me. can you review it?

**Comment by berkayalkan** [comment]
Customer scenario is revised by @olcaytoturker and me. Can you check it?
