### ISSUE TITLE
Making changes on project with feedbacks from the customer meeting

### ISSUE THREAD

**Issue by koraycetiin** [bounswe/bounswe2020group4#42]
Here is the customer meeting notes.
https://github.com/bounswe/bounswe2020group4/wiki/Customer-Meeting-Notes-%231-(02.03.2020)
I've extracted action items from the meeting and divided the actions by three. 

Taking an action if required by examining the questions: 2, 3, 4, 6, 7, 9
Taking an action if required by examining the questions: 10, 11, 14, 15, 17
Taking an action if required by examining the questions: 18(non-functional requirement), 19 and discussions: 1, 2, 6

Edit: 
- [x] Task 1: Questions 2, 3, 4, 6 @berkeozdemir2016400246 
- [x] Task 2: Questions 7, 9, 10 @katakor 
- [x] Task 3: Questions 11, 14, 15 @eylulyalcinkaya 
- [x] Task 4: Questions 17, 18, 19  @berkayalkan 
- [x] Task 5: Discussion 1, 2, 6 @egirgin 

until **08.03.2020 Sunday @23.59**.

**Comment by egirgin** [comment]
I have made a few changes to the requirements.

Old:

> 1.1.3 Sign up
>
>1.1.3.1 Customer and vendor users shall provide data according to their user type.
>1.1.3.2 E-mail addresses should be unique.
>1.1.3.3 User passwords should be in the specified form.
>1.1.3.4 Using Google account for signing up/in shall be a plus.
>1.1.3.5 During registration, the email address should be verified.

New:

>1.1.3 Sign up
>
>1.1.3.1 Customer and vendor users shall provide an e-mail and a password while they are signing up. Besides, vendors shall provide their location during registration.
>1.1.3.2 E-mail address and user type pairs should be unique. (i.e. there can be a customer and a vendor accounts using the same e-mail.)
>1.1.3.3 User passwords should be in the form of alphanumeric and at least 6 characters long.
>1.1.3.4 Google account should be used for signing up/in.
>1.1.3.5 During registration, the email address should be verified.

Also added a subtitle to the System Requirements: (for discussion 6)

>1.2.8 Payment
>
>1.2.8.1 When a customer makes a purchase, the platform keeps the money for three days. When the user approves that he/she got the product, money must be transferred to the vendor.
>1.2.8.2 If the cargo has not arrived to the customer yet, the customer can extend the period for approval of the product.

Please let me know if these changes create a **conflict with other requirements**.

Also, @eylulyalcinkaya If you want to add some requirements related to Question 11, you may want to use the `Payment` subtitle I just added.

**Comment by berkayalkan** [comment]
I have changed the requirements 1.1.1.1.9 and 1.1.1.1.10 according to Q17, added 2.1.7 according to Q18. Also I have added 1.1.1.1.15, 1.1.1.2.5, 1.1.1.3.4 and 1.1.1.4.2 according to Q19.

**Comment by eylulyalcinkaya** [comment]
Here are the changes I have made:

Under the section **Payment**
> * **1.2.8.3** Customer must approve an e-commerce shopping agreement to be able to make the payment.

Under the section **Vendor**
> * **1.1.1.2.6** Vendors shall be able to make a discount on a product for a certain time span.
> * **1.1.1.2.7** Vendors shall be able to create campaigns for certain products for a certain time span.
> * **1.1.1.2.8** Vendors can not make purchases using their vendor account.

I have also added *Campaign* to glossary:
> * **Campaign:** Campaigns include making discounts for buying in bulk (discount on a single product is not included) such as but not limited to: buying 3 items but paying for 2, discount of 10% for orders more than 100 TL, free shipment.

**Comment by katakor** [comment]
Q7: added to Search
> * **1.2.1.1.3** Searching Mechanism shall include combinative search.
>     * **1.2.1.1.3.1** Searching Mechanism shall enable searching for an item and sorting the results by price.
>     * **1.2.1.1.3.2** Searching Mechanism should enable searching for an item and sorting the results by other features, such as color.

Q9: added to Interface
> * **1.2.3.2** All user types (Guest, Customer, Vendor, Admin) shall have different interfaces.

Q10: tried to make the whole process more understandable by rearranging Customer requirements
> * **1.1.1.1.1** Customers shall be able to search for products.
> * **1.1.1.1.2** Customers shall be able to filter searched products based on average customer review, brand, vendor, and price range.
> * **1.1.1.1.3** Customers shall be able to sort searched products based on best-selling, latest arrival time,  price, average customer review, number of comments, and rating.
> * **1.1.1.1.4** Customers shall be able to create **Wishlists**.
>      * **1.1.1.1.4.1** Customers shall be able to save a wishlist, to purchase the same list of items multiple times.
> * **1.1.1.1.5** Customers shall have a **Cart** page.  
>	 * **1.1.1.1.5.1** Customers shall be able to add products to their Cart.
>	 * **1.1.1.1.5.2** Customers shall be able to purchase all items from their Cart at once.
> * **1.1.1.1.6** Customers shall have an **Orders page**.  
>	  * **1.1.1.1.6.1** Customers shall be able to see all their purchased items in the Orders page.
>	  * **1.1.1.1.6.2** Customers shall be able to cancel their active orders in the Orders page before they have been shipped.
>	  * **1.1.1.1.6.3** After the items have been shipped, customers shall be able to return the delivered orders in the Orders page.
>	  * **1.1.1.1.6.4** Customers shall be able to see total amount of money they have spent so far in the Orders page. The total differs based on the actions the customer has taken, such as returning an item or cancelling an order.
> * **1.1.1.1.7** Customers shall be able to receive notifications.
>	  * **1.1.1.1.7.1** Customers shall be notified when an order is delivered.
>	  * **1.1.1.1.7.2** Customers shall be able to choose to be notified if the price of a chosen product changes.
>	  * **1.1.1.1.7.3** Customers shall be able to choose to be notified if a product that is out of stock is available again.
> * **1.1.1.1.8** Customers shall be able to comment on products.
> * **1.1.1.1.9** Customers shall be able to rate products.
> * **1.1.1.1.10** Customers shall be able to access the platform from any software device.
