### ISSUE TITLE
Voting on a project name

### ISSUE THREAD

**Issue by berkeozdemir2016400246** [bounswe/bounswe2020group4#43]
We need to decide on a project name and logo

Please vote at
https://www.strawpoll.me/19524476

You can check the logos for each of the options at https://github.com/bounswe/bounswe2020group4/wiki/Ideas-for-project-name-and-logo

**Comment by zeritte** [comment]
guys, I know these are hard days but can you spare 2 minutes to vote? We can finalize this after 2 more votes I think.

**Comment by zeritte** [comment]
hi again! according to [results](https://www.strawpoll.me/19524476/r) "Buyo" won the poll. updating the homepage according to that.
