### ISSUE TITLE
Creating class diagram

### ISSUE THREAD

**Issue by zeritte** [bounswe/bounswe2020group4#44]
As it is stated in the PS and homework; we need to create a class diagram as a group. Respective group members are assigned. **Deadline: 21.03.2020 Saturday@23.59**

**Comment by egirgin** [comment]
A useful [link](https://www.guru99.com/uml-class-diagram.html)

**Comment by cagric0** [comment]
https://www.lucidchart.com/invitations/accept/397694e6-ca48-4980-a4a3-82866556b0cf

You can access class diagram from the link and please give some feedback

**Comment by egirgin** [comment]
We got feedback on diagrams via Piazza by Meriç Turan (@mericturan). Please check if you handle any of the following tasks and add your GitHub username end of that task. 

Please update both Google Sheet and LucidChart Diagram if necessary.

***

- [ ] There are some inconsistencies between the class names. Here is an example: “AdminUser” and “Registered User”. It is better to decide one notation and stick with it. The notation issues continue in the rest of your class diagram.

- [ ] Class for Guest user type is missing, so there is no class about registration. It is a big deficiency.

- [ ]  There are other missing classes as well such as class related to payment details.

- [ ] Utils class has no relationship with any other class. Why?

- [ ] Class attributes are needed to be more comprehensive. For example, for Location class, there can be many other attributes such as address name, postal code.

Class operations (i.e., methods) are also needed to be more comprehensive.

- [ ]  For example, for Location class, how about updateLocation or deleteLocation methods?

- [ ] Another example, how about agreement for GDPR/KVKK while signing-up.

There is no one right choice about class relationships. Yet, some of your choices seem questionable to me.

- [ ] For example, there is a composition relationship between Date and Order classes. I think Date class can survive without having Order class. 

- [ ] Another example can be given about the inheritance relationship. AdminUser, VendorUser, and CustomerUser classes are inherited from Registered User class. Unfortunately, the inheritance relationship notation is wrong in your class diagram. 

- [ ] On the other hand, there shouldn’t be an inheritance relation between Order and Product classes, but there is according to your class diagram. Also, there is no relationship names.

**Comment by egirgin** [comment]
The final version can be found [here](https://github.com/bounswe/bounswe2020group4/blob/master/deliverables/M1-Group4.pdf).
