### ISSUE TITLE
Creating use case diagram

### ISSUE THREAD

**Issue by zeritte** [bounswe/bounswe2020group4#45]
As it is stated in the PS and homework; we need to create a class diagram as a group. Respective group members are assigned. **Deadline: 21.03.2020 Saturday@23.59**

**Comment by burakcuhadar** [comment]
Here is the link to the use case diagram: https://www.lucidchart.com/invitations/accept/958a3910-5ebe-4ca7-b9f8-dc3e7cf6ee59.

**Comment by koraycetiin** [comment]
wiki link of the use case diagram https://github.com/bounswe/bounswe2020group4/wiki/Use-Case-Diagram
