### ISSUE TITLE
Creating sequence diagrams

### ISSUE THREAD

**Issue by zeritte** [bounswe/bounswe2020group4#46]
In the 5th meeting, we decided everyone except Erdinç to create a sequence diagram. (Erdinç has some other tasks) **Deadline: 23.03.2020 Monday@23.59**

- [x] Burak Çuhadar
- [x] Koray Çetin
- [x] Eylül Yalçınkaya
- [x] Emre Girgin
- [x] Salih Kasım Benli
- [x] Berke Özdemir
- [x] Katariina Korolainen
- [x] Berkay Alkan
- [ ] Muhammed Olcayto Türker
- [x] Çağrı Çiftçi

**Comment by koraycetiin** [comment]
Please upload your diagrams to diagrams/state_diagrams folder

**Comment by egirgin** [comment]
The final version can be found [here](https://github.com/bounswe/bounswe2020group4/blob/master/deliverables/M1-Group4.pdf).
