### ISSUE TITLE
Listing future work for the ProjectPlan

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#51]
For the sake of the assignment about ProjectPlan, we need to list our future work. Thus, those tasks are needed to be listed in Google Sheet.

- [x] Emre Girgin @egirgin (Milestones) Deadline : **18.04.2020 Saturday@23.59**

- [x] Mehmet Erdinç Oğuz @eridincu (Future work other than milestones) **18.04.2020 Saturday@23.59**

- [x] Katariina Korolainen @katakor (Assignment of future work) **19.04.2020 Sunday@23.59** 

- [x] Katariina Korolainen @katakor (Transferring to [ProjectLibre](https://www.projectlibre.com/)) **20.04.2020 Monday@23.59**

**Comment by katakor** [comment]
[Project Plan](https://github.com/bounswe/bounswe2020group4/wiki/Project-Plan)

**Comment by eridincu** [comment]
Adding next semester's work to the Project Plan.

**Comment by eridincu** [comment]
https://github.com/bounswe/bounswe2020group4/blob/master/Gantt_3.pdf
This is the PDF file for the latest Gantt.
https://github.com/bounswe/bounswe2020group4/blob/master/Gantt_3.pod
This is the Project Libre file.
