### ISSUE TITLE
Applying some APIs' token.

### ISSUE THREAD

**Issue by cagric0** [bounswe/bounswe2020group4#55]
Deadline: 08.05.2020 Friday@23.59

**Comment by eridincu** [comment]
I rece,ved "eBay" and "Google-Products" API auth tokens.

**Comment by egirgin** [comment]
Some tokens are found and discussed. Details can be found [here](https://github.com/bounswe/bounswe2020group4/wiki/Meeting-Notes-%239-(10.05.2020))
