### ISSUE TITLE
About Mobile Application

### ISSUE THREAD

**Issue by mericturan** [bounswe/bounswe2020group4#563]
Dear Android developers,

Can one or more of you attend an online meeting and provide some guidance to me about your Android application tomorrow (February 3, Wednesday)?

If so, I am open for time suggestions.

**Comment by egirgin** [comment]
Dear @mericturan hocam,

We can meet at 13.00 o'clock if you are available. You or we can send the meeting link if this is OK for you.

**Comment by mericturan** [comment]
13:00 is fine by me.

We can meet via Google Meet using the following link: https://meet.google.com/ocd-wwwx-ryj.

**Comment by mericturan** [comment]
Thanks for your participation.
