### ISSUE TITLE
Making labels custom

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#6]
I have created some custom labels regarding the projects of the last year. Please check them out.
And please share your reviews and suggestions under this issue.

**Comment by egirgin** [comment]
I wrote a guide about labels: [Labels Guide](https://github.com/bounswe/bounswe2020group4/wiki/Labels-Guide)

**Comment by eridincu** [comment]
Looks great. I think we can also update the labels in the future as we make progress.

**Comment by koraycetiin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Making Labels Custom](https://trello.com/c/ROOxh03t/38-making-labels-custom)
