### ISSUE TITLE
Implementing individual endpoints

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#67]
Implementation Assignment.

11 endpoints are needed to be implemented and tested with at least a unit test.

@zeritte is assigned as well but couldn't added due to limits on the number assignees.

Deadline: **18.05.2020**

- [x] Berkay Alkan
- [x] Salih Kasım Benli
- [x] Koray Çetin
- [x] Çağrı Çiftçi
- [x] Burak Çuhadar
- [x] Emre Girgin
- [x] Katariina Korolainen
- [x] Mehmet Erdinç Oğuz
- [x] Ali Berke Özdemir
- [x] Muhammed Olcayto Türker
- [x] Eylül Yalçınkaya

**Comment by zeritte** [comment]
everyone completed his/her endpoint work
