### ISSUE TITLE
vendor/nearest endpoint API restriction

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#69]
I cloned the repo and tested **/vendor/nearest** endpoint using Postman. I got the following response.

```python
{
    "status": {
        "success": false,
        "code": 404
    },
    "error": "The provided API key has an IP address restriction. The originating IP address of the call (<my_IP_address>) violates this restriction."
}
```

Is it just me or does Google restrict the usage of geolocation API?
@koraycetiin maybe you want to check.

**Comment by koraycetiin** [comment]
I've restricted it with my ip, this response is OK
