### ISSUE TITLE
Research about Github/Wiki/Git

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#7]
All of us is wanted to do some research about Github/Wiki/Git for the first assignment. We can share useful links under this issue.

Edit: Don't forget to update your Personal Effort Document

**Comment by zeritte** [comment]
https://www.markdownguide.org/basic-syntax/ here is a link for markdown language that we talked about during the lecture

**Comment by koraycetiin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Research about Github/Wiki/Git](https://trello.com/c/1wlQl1ml/37-research-about-github-wiki-git)
