### ISSUE TITLE
Creating a Configuration File for the API Keys

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#70]
Today, instructor said that we shouldn't include API keys in our code.

Instead of that, we are required to create a configuration file that stores the API keys in a safe place and we should be able to get them when we execute the code. 

I thought it should be brought up since we are creating our endpoints.

**Comment by zeritte** [comment]
dot-env package can be used to do that. which programming language and framework are we going to use? it is not available in the meeting notes

**Comment by koraycetiin** [comment]
i can do it

**Comment by koraycetiin** [comment]
https://github.com/bounswe/bounswe2020group4/pull/72 here is the pull request
