### ISSUE TITLE
Writing a wiki page about Git

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#8]
We are asked to write a wiki page about Git in the first assignment. Here is an example from the last year: https://github.com/bounswe/bounswe2019group7/wiki/GitHub-Tutorial

The video mentioned in assignment #1 .
Git For Ages 4 And Up - https://youtu.be/1ffBJ4sVUb4

**Comment by egirgin** [comment]
The link in the sidebar seems has the URL https://github.com/bounswe/bounswe2020group4/wiki/GitHub-Tutorial#repo instead of https://github.com/bounswe/bounswe2020group4/wiki/GitHub-Tutorial . 
I fixed that and the rest is well done. 👍

**Comment by eridincu** [comment]
Updated the name of the page to "Git Tutorial" from "GitHub Tutorial" since the tutorial is not about github but more about Git itself. We can discuss more about it tomorrow.
