### ISSUE TITLE
Merging the endpoint pull requests

### ISSUE THREAD

**Issue by koraycetiin** [bounswe/bounswe2020group4#82]
Pull requests of 11 endpoints should be merged to master.

Deadline: **21/05/2019**

Endpoints of members below are merged.

- [x] Berkay Alkan
- [x] Salih Kasım Benli
- [x] Koray Çetin
- [x] Çağrı Çiftçi
- [x] Burak Çuhadar
- [x] Emre Girgin
- [x] Katariina Korolainen
- [x] Mehmet Erdinç Oğuz
- [x] Ali Berke Özdemir
- [x] Muhammed Olcayto Türker
- [x] Eylül Yalçınkaya

**Comment by zeritte** [comment]
merging completed. see commits
