### ISSUE TITLE
Writing personal page on Wiki

### ISSUE THREAD

**Issue by egirgin** [bounswe/bounswe2020group4#9]
While we are exploring the repositories from previous years, we realized that there is a wiki page for each member of the project. We thought that is a good idea.
@burakcuhadar made his page already. Please check that out: https://github.com/bounswe/bounswe2020group4/wiki/Burak-%C3%87uhadar

You may add some areas of interest and a photo maybe.

Please share your opinions and write a wiki page about yourself if you want to.  

Also, @olcaytoturker is the assignee as well.

**After the feedback of Assignment1**

At the feedback of Assignment1, we are asked to add more specific information about ourselves. TA @mericturan said "In your personal wiki page, you should specify more information than “Student of Computer Engineering at Bogazici University”." 

We are going to update our pages.

Creating personal wiki page.
- [x] @olcaytoturker 
- [x] @cagric0 

Adding spesific information about ourselves.
- [x] @egirgin 
- [x] @burakcuhadar 
- [x] @zeritte 
- [x] @eridincu 
- [x] @eylulyalcinkaya 
- [x] @berkayalkan 
- [x] @koraycetiin 
- [x] @berkeozdemir2016400246 
- [x] @katakor

**Comment by koraycetiin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Writing Personal Page on Wiki](https://trello.com/c/6FAs6o47/35-writing-personal-page-on-wiki)
