### ISSUE TITLE
Nearest Hospital Endpoint Null Response

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#97]
Nearest Hospital endpoint returns null response when after it receives the body.

1. Go to Postman
2. Set lat, long and radius values to 41.0862, 29.0444, 2000, respectively.
3. Scroll down to result.
4. Count should be 0, and the names array should be empty

It is expected to receive nearest hospitals. For these values, "Baltalimanı Family Health Center", "Üsküdar University NP Etiler Medical Center" is expected as the correct response with count value being equal to "2".

The screenshot for the test in postman is below.

![image](https://user-images.githubusercontent.com/38115703/82740524-24e3a800-9d52-11ea-9805-57c8da2a2032.png)

**Comment by zeritte** [comment]
this is not the correct way to send the data to nearestHospital endpoint. instead, you should do the following with postman: (see body & type of the object (JSON))
<img width="807" alt="Screen Shot 2020-05-24 at 00 35 23" src="https://user-images.githubusercontent.com/35241861/82740994-7e4dd600-9d56-11ea-959e-cf274975735f.png">

**Comment by egirgin** [comment]
Merged.
